[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['md', 'markdown']
hook_add = '''
  let g:vim_markdown_folding_disabled = 1
'''

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']

[[plugins]]
repo = 'hashivim/vim-terraform''
on_ft = ['tf']
hook_add = '''
  let g:terraform_fmt_on_save=1
'''

[[plugins]]
repo = 'juliosueiras/vim-terraform-completion'
on_ft = ['tf']

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'tyru/open-browser-github.vim'
