[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']

[[plugins]]
repo = 'hashivim/vim-terraform''
on_ft = ['tf']
hook_add = '''
  let g:terraform_fmt_on_save=1
'''

[[plugins]]
repo = 'juliosueiras/vim-terraform-completion'
on_ft = ['tf']
